package controlstructuresprograms;

import java.util.Scanner;

public class DoWhileLoopGuessNumber 
{
	private void guessRandomNumber()
	{
		int num;  //this number holds randomly generated by  computer
		int guess;     //to holds the number guessed by the user.
		Scanner scobj=new Scanner(System.in);
				//generate the random number
				num = (int) (Math.random()*100);
					
				
		do 
		{
		System.out.println("ENTER THE GUESS NUMBER");
		guess=scobj.nextInt();
		
				if(guess==num)
				{
					System.out.println("YOUR GUEESED NUMBER IS CORRECT");
				}
				else if (guess>num)
				{
					System.out.println("YOUR GUESSED NUMBER IS BIGGER THEAN RANDOM NUMBER try again");
				}
				else if (guess<num)
				{
					System.out.println("YOUR GUESSED NUMBER IS SMALLER THAN RANDOM NUMBER");
				}
					
			} while(guess!=num);
			
		}
	
	
	
	

	public static void main(String[] args) {
		//calling non staic methods we need to create object creation
		DoWhileLoopGuessNumber ranobj=new DoWhileLoopGuessNumber();
		//calling non static method using obj ref.nonstaitc method name()
		ranobj.guessRandomNumber();
		
		
	}

}
